### ISSUE TITLE
pretrain model for feature extractor in 50salads

### ISSUE THREAD

**Issue by habakan** [ttlmh/Bridge-Prompt#12]
Hi! Thanks for your great work.
I tried to extract features from 50salads dataset using this command.
```
python extract_frame_features.py --config ./configs/salads/salads_exfm.yaml --dataset 50salads
```
I don't know why this yaml file reference breakfast pretrain model path.
https://github.com/ttlmh/Bridge-Prompt/blob/master/configs/salads/salads_exfm.yaml#L1
If I re-experment your works in 50 salads dataset, should I modify salads configs?
(example:  salads/20211111_121454_splt1/last_model.pt in your upload file)

Thanks.

**Comment by ttlmh** [comment]
That's right! You need to modify the model path to the downloaded .pt file.

**Comment by habakan** [comment]
Thanks for your comments!
I understood. and, I'll try it.
I appreciate it!

**Comment by XuanHien304** [comment]
@habakan  Hi Habakan, Can I ask you the step for extract frame-wise feature and the labels as well as on other dataset such as my own video dataset
