### ISSUE TITLE
Which dataset version should be downloaded

### ISSUE THREAD

**Issue by laohuijiadezhu** [ttlmh/Bridge-Prompt#14]
Hello, thank you very much for your detailed README and answers of issues.
According to README, I click the links to enter the official websites of Breakfast and GTEA. However, several download options were found for raw video. 
Breakfast:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/59173157/197694685-aafef2df-da83-414c-9134-45b5f3502071.png">
GTEA:
![image](https://user-images.githubusercontent.com/59173157/197694998-2dc5be28-7ee7-4034-9b7c-baed7c9c989b.png)

I don't know which to choose. Can you tell me your choice? I look forward to your reply!

**Comment by ttlmh** [comment]
You should download all the **videos** for our project.

**Comment by laohuijiadezhu** [comment]
Thanks! Videos or videos as videos as multipart files? Which is your choice?
<img width="544" alt="image" src="https://user-images.githubusercontent.com/59173157/198042947-5b449ff4-f551-43ed-8a03-f2552eeff9c2.png">
