### ISSUE TITLE
Issue downloading pre-trained weights from Baidu

### ISSUE THREAD

**Issue by julialromero** [ttlmh/Bridge-Prompt#22]
Hello,

I am trying to download the pre-trained model weights for action segmentation on 50 Salads. I am unable to make a Baidu account to download the weights because I am located overseas in the USA. Are the model weights uploaded anywhere else (like Zenodo, etc) that I can access? 

Thanks,
Julia

**Comment by HankKung** [comment]
@julialromero Hi have you solved this issue? I'm facing the same problem, it would be great to have your suggestion.
